### PR TITLE
Create rw.html

### PR DESCRIPTION
**Pull request by routermaven**

### CODE REVIEW

**Comment by routermaven** [comment]
Evil olive.

**Comment by routermaven** [comment]
Resolves #18

**Comment by mrmorris** [comment]
👍

**Comment by routermaven** [comment]
Flee to me, remote elf.

**Comment by routermaven** [comment]
Lisa Bonet ate no basil.

**Comment by routermaven** [comment]
Mr. Owl Ate My Metal Worm.

**Comment by routermaven** [comment]
O Bobo! Get Indy clear! He'd render a red nerd eh? Ra! El Cid nite! Go Bobo!

**Comment by routermaven** [comment]
Was raw tap ale not a reviver at one lap at Warsaw?

**Pull request merged**
